'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {createHash}=require('node:crypto');
const BOOK=require('../content.js');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ps=lines=>(lines||[]).map(p=>`<p>${esc(p)}</p>`).join('\n');
function build(){
  const styleVersion=createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../style.css'))).digest('hex').slice(0,12);
  const toc=BOOK.pages.map(p=>`<li><a href="#${p.id}">${esc(p.title)}</a></li>`).join('\n');
  const chapters=BOOK.pages.map((p,i)=>`<section id="${p.id}"><p class="edition-kicker">${i===0?'開場':p.kind==='reflection'?'故事以外':'故事'} · ${String(i).padStart(2,'0')}</p><h2>${esc(p.title)}</h2>${p.subtitle?`<p class="edition-subtitle">${esc(p.subtitle)}</p>`:''}${ps(p.paragraphs)}${p.quote?`<blockquote>${esc(p.quote.text)}<cite>${esc(p.quote.by)}</cite></blockquote>`:''}${ps(p.reveal)}${p.crystals?`<ol>${p.crystals.map(c=>`<li><strong>${esc(c.label)}</strong>：${esc(c.detail)}</li>`).join('')}</ol>`:''}${p.perspectives?p.perspectives.map(q=>`<aside><h3>${esc(q.name)}</h3><p>${esc(q.text)}</p></aside>`).join(''):''}${['initial','questions'].includes(p.interaction)?`<ol>${BOOK.questions.map(q=>`<li>${esc(q.prompt)}</li>`).join('')}</ol><p>你可以先留下想法，再讀辛格的論點；讀過之後，看看有沒有想補充的地方。</p>`:''}${p.note?`<aside><h3>${esc(p.note.type)}：${esc(p.note.label)}</h3><p>${esc(p.note.text)}</p>${p.note.source?`<a href="${BOOK.sources[p.note.source]}">對照法文原文</a>`:''}${p.note.locator?`<p class="source-reference">辛格《The Nature of Love》第二卷，${esc(p.note.locator)}</p>`:''}</aside>`:''}<p class="edition-return"><a href="index.html#${p.id}">在立體書中讀這一頁 ↗</a></p></section>`).join('\n');
  return `<!doctype html>\n<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="司湯達〈埃內斯蒂娜〉故事節述與辛格的哲學導讀，完整文字與來源註釋。"><title>愛，如何誕生｜完整文字版</title><link rel="icon" href="favicon.svg"><link rel="stylesheet" href="style.css?v=${styleVersion}"></head><body class="reading-edition"><header><a href="index.html">← 回到立體書</a><p class="edition-kicker">完整文字版</p><h1>愛，如何誕生</h1><p>故事節述與哲學導讀。所有紙瓣與結尾均已展開，無須啟用 JavaScript。</p></header><main><nav aria-label="章節目錄"><details><summary>目錄</summary><ol>${toc}</ol></details></nav>${chapters}<section id="sources"><h2>來源與改編說明</h2><p>這是中文節述，並非逐句全譯。七階段是文學與心理分析，不是科學量表。人物的心聲、敘述者的解釋、辛格的論點與本書提出的問題分開標示。</p><ol><li><a href="${BOOK.sources.story}">司湯達〈Ernestine, ou la naissance de l’amour〉法文故事</a></li><li><a href="${BOOK.sources.stages}">司湯達《論愛情》第二章〈愛的誕生〉</a></li><li>Irving Singer，<em>The Nature of Love</em>，第二卷 <em>Courtly and Romantic</em>，第十一章。依據本專案提供的文本節述，以段首定位，不重刊整章。</li></ol><h3>七階段書籤</h3><ol>${BOOK.stages.map(s=>`<li><a href="#${s.page}">${esc(s.name)}</a>：${esc(s.description)}</li>`).join('')}</ol><p>插畫及紙藝素材以 AI 輔助製作。司湯達與辛格的相遇屬想像場景。</p></section></main><footer><a href="index.html">回到立體書</a> · <a href="https://github.com/remtoec/stendhal">原始碼</a></footer></body></html>\n`;
}
if(require.main===module)fs.writeFileSync(path.join(__dirname,'../read.html'),build());
module.exports=build;
